from __future__ import annotations

import base64
import os
import shutil
import subprocess
import types
from pathlib import Path

import requests
import typer
from atlassian import Confluence as _Confluence
from atlassian import Jira as _Jira
from rich.console import Console
from rich.panel import Panel

from atlassian_cli.integrations.ollama import OllamaClient

app = typer.Typer(help="Initialize and configure a project")
console = Console()


def _atlassian_session(cls, url: str, email: str, token: str):
    """Instantiate an atlassian client with UTF-8 Basic auth.

    requests._basic_auth_str encodes credentials as latin-1, which raises
    UnicodeEncodeError for any non-latin-1 character. We bypass it by setting
    the Authorization header directly using UTF-8 (RFC 7617).
    """
    client = cls(url=url, cloud=True)
    auth = base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")
    client._session.headers["Authorization"] = f"Basic {auth}"
    client._session.auth = None  # prevent any residual session auth from interfering
    return client


@app.callback()
def _group() -> None:
    """Project setup and configuration commands."""


def _ollama_list_models(host: str) -> list[str]:
    try:
        resp = requests.get(f"{host}/api/tags", timeout=5)
        resp.raise_for_status()
        return [m["name"] for m in resp.json().get("models", [])]
    except Exception:
        return []


def _ollama_pull(model: str) -> bool:
    try:
        result = subprocess.run(["ollama", "pull", model], timeout=300)
        return result.returncode == 0
    except Exception:
        return False


def _turso_available() -> bool:
    """Return True only if turso CLI is actually runnable (not just present on disk).

    shutil.which finds .cmd wrappers on Windows but subprocess can't run them
    without shell=True. This function probes with a real invocation to avoid
    false positives.
    """
    try:
        result = subprocess.run(
            ["turso", "--version"],
            capture_output=True,
            timeout=5,
            shell=(os.name == "nt"),
        )
        return result.returncode == 0
    except Exception:
        return False


def _turso_create_db(db_name: str) -> tuple[str, str]:
    _sh = os.name == "nt"  # .cmd wrappers on Windows require shell=True
    subprocess.run(["turso", "db", "create", db_name], check=True, shell=_sh)
    url = subprocess.run(
        ["turso", "db", "show", db_name, "--url"],
        capture_output=True, text=True, check=True, shell=_sh,
    ).stdout.strip()
    token = subprocess.run(
        ["turso", "db", "tokens", "create", db_name],
        capture_output=True, text=True, check=True, shell=_sh,
    ).stdout.strip()
    return url, token


def _ensure_gitignored(env_path: Path) -> None:
    """Append .env to .gitignore if a git repo is detected and the file isn't already ignored."""
    gitignore = Path(".gitignore")
    if not Path(".git").exists():
        return
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    if any(
        line.strip() in (".env", "*.env", ".env*")
        for line in existing.splitlines()
    ):
        return
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write("\n.env\n" if existing and not existing.endswith("\n") else ".env\n")
    console.print("[dim]Added .env to .gitignore[/dim]")


def _write_env(values: dict, path: Path) -> None:
    lines = [
        "# Generated by atlassian project init",
        f"ATLASSIAN_URL={values['atlassian_url']}",
        f"ATLASSIAN_EMAIL={values['atlassian_email']}",
        f"ATLASSIAN_API_TOKEN={values['atlassian_api_token']}",
        f"JIRA_PROJECT={values['jira_project']}",
        f"CONFLUENCE_SPACE={values['confluence_space']}",
        f"OLLAMA_HOST={values['ollama_host']}",
        f"OLLAMA_MODEL={values['ollama_model']}",
        f"OLLAMA_EMBED_MODEL={values['ollama_embed_model']}",
        "MEMORY_DB_PATH=~/.atlassian-cli/memory.db",
        "MEMORY_VECTOR_PATH=~/.atlassian-cli/vectors/",
        f"QA_BASE_URL={values.get('qa_base_url', '')}",
        f"MEMORY_BACKEND={values['memory_backend']}",
    ]
    if values.get("turso_url"):
        lines.append(f"TURSO_URL={values['turso_url']}")
    if values.get("turso_auth_token"):
        lines.append(f"TURSO_AUTH_TOKEN={values['turso_auth_token']}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@app.command("init")
def init() -> None:
    """Interactive wizard to configure a new atlassian-cli project."""
    console.print(Panel(
        "Welcome to [bold]atlassian-cli[/bold] project setup.\n"
        "This wizard creates a [bold].env[/bold] file in the current directory.",
        title="[cyan]atlassian project init[/cyan]",
    ))

    env_path = Path(".env")
    if env_path.exists():
        if not typer.confirm("\n.env already exists. Overwrite?", default=False):
            console.print("[dim]Cancelled.[/dim]")
            raise typer.Exit(0)

    collected: dict = {}

    # ── Step 1: Credentials ──────────────────────────────────────────────
    console.print("\n[bold]Step 1/5[/bold] — Atlassian Credentials")
    collected["atlassian_url"] = typer.prompt(
        "  Atlassian URL", default="https://yourorg.atlassian.net"
    ).rstrip("/")
    collected["atlassian_email"] = typer.prompt("  Email").strip()
    while True:
        token = typer.prompt("  API Token", hide_input=True).strip()
        if not token:
            console.print("  [red]Token cannot be empty, try again.[/red]")
            continue
        token2 = typer.prompt("  Confirm API Token", hide_input=True).strip()
        if token == token2:
            collected["atlassian_api_token"] = token
            console.print(f"  [dim]Token accepted ({len(token)} chars)[/dim]")
            break
        console.print("  [red]Tokens don't match, try again.[/red]")

    _jira = _atlassian_session(
        _Jira, collected["atlassian_url"],
        collected["atlassian_email"], collected["atlassian_api_token"],
    )
    _conf = _atlassian_session(
        _Confluence, collected["atlassian_url"],
        collected["atlassian_email"], collected["atlassian_api_token"],
    )

    # Verify credentials before proceeding
    with console.status("[bold green]Verifying credentials…[/bold green]"):
        try:
            _me = _jira.myself()
            _account_id = _me.get("accountId") if isinstance(_me, dict) else None
            console.print("[green]✓[/green] Credentials verified")
        except Exception as exc:
            msg = str(exc).lower()
            if "401" in str(exc) or "not authenticated" in msg or "unauthorized" in msg:
                console.print("[red]✗ Authentication failed.[/red] Check your email and API token.")
                console.print(
                    "  Create a token at: "
                    "[link=https://id.atlassian.com/manage-profile/security/api-tokens]"
                    "https://id.atlassian.com/manage-profile/security/api-tokens[/link]"
                )
            else:
                console.print(f"[red]✗[/red] Could not connect to Jira: {exc}")
            raise typer.Exit(1)

    # ── Step 2: Jira project ─────────────────────────────────────────────
    console.print("\n[bold]Step 2/5[/bold] — Jira Project")
    jira_choice = typer.prompt(
        "  (n) Create new project  (e) Use existing", default="e"
    ).strip().lower()

    if jira_choice == "n":
        proj_name = typer.prompt("  Project name")
        proj_key = typer.prompt("  Project key (e.g. MYAPP)").upper()
        with console.status("[bold green]Creating Jira project...[/bold green]"):
            try:
                payload: dict = {
                    "key": proj_key,
                    "name": proj_name,
                    "projectTypeKey": "software",
                }
                if _account_id:
                    payload["leadAccountId"] = _account_id
                _jira.create_project_from_raw_json(payload)
                console.print(f"[green]✓[/green] Created Jira project: {proj_key}")
            except Exception as exc:
                console.print(f"[red]✗[/red] Failed to create project: {exc}")
                raise typer.Exit(1)
        collected["jira_project"] = proj_key
    else:
        proj_key = typer.prompt("  Project key", default="MYAPP").upper()
        try:
            _jira.project(proj_key)
            console.print(f"[green]✓[/green] Found Jira project: {proj_key}")
        except Exception:
            console.print(f"[yellow]⚠[/yellow]  Could not verify project {proj_key} — continuing")
        collected["jira_project"] = proj_key

    # ── Step 3: Confluence space ─────────────────────────────────────────
    console.print("\n[bold]Step 3/5[/bold] — Confluence Space")
    conf_choice = typer.prompt(
        "  (n) Create new space  (e) Use existing", default="e"
    ).strip().lower()

    if conf_choice == "n":
        space_name = typer.prompt("  Space name")
        space_key = typer.prompt("  Space key (e.g. DEV)").upper()
        with console.status("[bold green]Creating Confluence space...[/bold green]"):
            try:
                _conf.create_space(space_name, space_key)
                console.print(f"[green]✓[/green] Created Confluence space: {space_key}")
            except Exception as exc:
                console.print(f"[red]✗[/red] Failed to create space: {exc}")
                raise typer.Exit(1)
        collected["confluence_space"] = space_key
    else:
        space_key = typer.prompt("  Space key", default="DEV").upper()
        try:
            _conf.get_space(space_key)
            console.print(f"[green]✓[/green] Found Confluence space: {space_key}")
        except Exception:
            console.print(f"[yellow]⚠[/yellow]  Could not verify space {space_key} — continuing")
        collected["confluence_space"] = space_key

    # ── Step 4: Ollama ───────────────────────────────────────────────────
    console.print("\n[bold]Step 4/5[/bold] — Ollama Model")
    collected["ollama_host"] = typer.prompt(
        "  Ollama host", default="http://localhost:11434"
    )
    models = _ollama_list_models(collected["ollama_host"])

    if models:
        console.print("  Available models:")
        for i, m in enumerate(models, 1):
            console.print(f"    {i}. {m}")
        console.print("  Enter a number to select, or type a model name to download it.")
        raw = typer.prompt("  Model", default="1")
        if raw.isdigit() and 1 <= int(raw) <= len(models):
            collected["ollama_model"] = models[int(raw) - 1]
        else:
            collected["ollama_model"] = raw
            if raw not in models:
                if typer.confirm(f"  Pull {raw}?", default=True):
                    with console.status(f"Pulling {raw}…"):
                        _ollama_pull(raw)
    else:
        console.print("  [dim](Ollama not reachable or no models installed)[/dim]")
        collected["ollama_model"] = typer.prompt("  Model name", default="llama3.2")

    embed_default = "nomic-embed-text"
    embed_hint = "[green]installed[/green]" if embed_default in models else "[yellow]not installed[/yellow]"
    collected["ollama_embed_model"] = typer.prompt(
        f"  Embed model  ({embed_hint})", default=embed_default
    )
    if collected["ollama_embed_model"] not in models:
        if typer.confirm(f"  Pull {collected['ollama_embed_model']}?", default=True):
            with console.status(f"Pulling {collected['ollama_embed_model']}…"):
                _ollama_pull(collected["ollama_embed_model"])

    collected["qa_base_url"] = typer.prompt(
        "  QA base URL (optional, for test runner)", default=""
    )

    # ── Step 5: Memory backend ───────────────────────────────────────────
    console.print("\n[bold]Step 5/5[/bold] — Memory Backend")
    console.print("  (l) Local SQLite — works offline")
    console.print("  (t) Turso        — shared across machines")
    backend_choice = typer.prompt("  Backend", default="l").strip().lower()

    if backend_choice == "t":
        collected["memory_backend"] = "turso"
        if _turso_available():
            console.print("  [green]turso CLI detected[/green]")
            turso_action = typer.prompt(
                "  (n) Create new database  (e) Use existing", default="n"
            ).strip().lower()
            if turso_action == "n":
                db_name = typer.prompt("  Database name", default="atlassian-memory")
                with console.status("[bold green]Creating Turso database...[/bold green]"):
                    try:
                        url, token = _turso_create_db(db_name)
                        collected["turso_url"] = url
                        collected["turso_auth_token"] = token
                        console.print("[green]✓[/green] Turso database created")
                        console.print(f"  [dim]URL: {url}[/dim]")
                    except Exception as exc:
                        console.print(f"[yellow]⚠[/yellow] Turso creation failed: {exc}")
                        console.print("  [dim]Falling back to local SQLite — you can switch later.[/dim]")
                        collected["memory_backend"] = "local"
            else:
                collected["turso_url"] = typer.prompt("  TURSO_URL (libsql://...)")
                collected["turso_auth_token"] = typer.prompt(
                    "  TURSO_AUTH_TOKEN", hide_input=True
                )
        else:
            console.print(
                "  [yellow]turso CLI not found.[/yellow]  "
                "Install: [bold]npm install -g turso[/bold]"
            )
            collected["turso_url"] = typer.prompt("  TURSO_URL (libsql://...)")
            collected["turso_auth_token"] = typer.prompt(
                "  TURSO_AUTH_TOKEN", hide_input=True
            )
    else:
        collected["memory_backend"] = "local"

    # ── Write .env ───────────────────────────────────────────────────────
    _write_env(collected, env_path)
    console.print(f"\n[green]✓[/green] Written: {env_path.resolve()}")
    _ensure_gitignored(env_path)

    # ── Verify connections ───────────────────────────────────────────────
    console.print("\n[bold]Verifying connections…[/bold]")

    try:
        _jira.project(collected["jira_project"])
        console.print(f"[green]✓[/green] Jira ({collected['jira_project']})")
    except Exception:
        console.print(f"[red]✗[/red]  Jira ({collected['jira_project']})")

    try:
        _conf.get_space(collected["confluence_space"])
        console.print(f"[green]✓[/green] Confluence ({collected['confluence_space']})")
    except Exception:
        console.print(f"[red]✗[/red]  Confluence ({collected['confluence_space']})")

    _mock = types.SimpleNamespace(
        ollama_host=collected["ollama_host"],
        ollama_model=collected["ollama_model"],
        ollama_embed_model=collected["ollama_embed_model"],
    )
    if OllamaClient(_mock).ping():
        console.print(f"[green]✓[/green] Ollama ({collected['ollama_model']})")
    else:
        console.print(f"[red]✗[/red]  Ollama (not reachable at {collected['ollama_host']})")

    if collected.get("turso_url"):
        from atlassian_cli.integrations.turso import TursoHttpClient
        try:
            TursoHttpClient(
                collected["turso_url"], collected.get("turso_auth_token", "")
            ).execute("SELECT 1")
            console.print(f"[green]✓[/green] Turso ({collected['turso_url']})")
        except Exception:
            console.print("[red]✗[/red]  Turso (connection failed)")

    console.print(
        f"\n[green]Done![/green] Run [bold]atlassian feature create[/bold] to get started."
    )
