from __future__ import annotations

import base64
import json
import os
import shutil
import subprocess
import types
from pathlib import Path

import requests
import typer
from atlassian import Confluence as _Confluence
from atlassian import Jira as _Jira
from rich.console import Console
from rich.panel import Panel

from atlassian_cli.integrations.ollama import OllamaClient

app = typer.Typer(help="Initialize and configure a project")
console = Console()


def _atlassian_session(cls, url: str, email: str, token: str):
    """Instantiate an atlassian client with UTF-8 Basic auth.

    requests._basic_auth_str encodes credentials as latin-1, which raises
    UnicodeEncodeError for any non-latin-1 character. We bypass it by setting
    the Authorization header directly using UTF-8 (RFC 7617).
    """
    client = cls(url=url, cloud=True)
    auth = base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")
    client._session.headers["Authorization"] = f"Basic {auth}"
    client._session.auth = None  # prevent any residual session auth from interfering
    return client


@app.callback()
def _group() -> None:
    """Project setup and configuration commands."""


def _ollama_list_models(host: str) -> list[str]:
    try:
        resp = requests.get(f"{host}/api/tags", timeout=5)
        resp.raise_for_status()
        return [m["name"] for m in resp.json().get("models", [])]
    except Exception:
        return []


def _ollama_pull(model: str) -> bool:
    try:
        result = subprocess.run(["ollama", "pull", model], timeout=300)
        return result.returncode == 0
    except Exception:
        return False


def _turso_available() -> bool:
    """Return True only if turso CLI is actually runnable (not just present on disk).

    shutil.which finds .cmd wrappers on Windows but subprocess can't run them
    without shell=True. This function probes with a real invocation to avoid
    false positives.
    """
    try:
        result = subprocess.run(
            ["turso", "--version"],
            capture_output=True,
            timeout=5,
            shell=(os.name == "nt"),
        )
        return result.returncode == 0
    except Exception:
        return False


def _turso_create_db(db_name: str) -> tuple[str, str]:
    _sh = os.name == "nt"  # .cmd wrappers on Windows require shell=True
    subprocess.run(["turso", "db", "create", db_name], check=True, shell=_sh)
    url = subprocess.run(
        ["turso", "db", "show", db_name, "--url"],
        capture_output=True, text=True, check=True, shell=_sh,
    ).stdout.strip()
    token = subprocess.run(
        ["turso", "db", "tokens", "create", db_name],
        capture_output=True, text=True, check=True, shell=_sh,
    ).stdout.strip()
    return url, token


_PROGRESS_FILE = Path(".atlassian-init-progress.json")
_STEP_NAMES = {
    2: "Jira Project",
    3: "Confluence Space",
    4: "Ollama Model",
    5: "Memory Backend",
}


def _load_progress() -> dict | None:
    if _PROGRESS_FILE.exists():
        try:
            return json.loads(_PROGRESS_FILE.read_text(encoding="utf-8"))
        except Exception:
            return None
    return None


def _save_progress(data: dict, completed_step: int) -> None:
    safe = {k: v for k, v in data.items() if k != "atlassian_api_token"}
    _PROGRESS_FILE.write_text(
        json.dumps({"version": 1, "completed_step": completed_step, "data": safe}, indent=2),
        encoding="utf-8",
    )


def _clear_progress() -> None:
    if _PROGRESS_FILE.exists():
        _PROGRESS_FILE.unlink()


def _ensure_gitignored(env_path: Path) -> None:
    """Append .env to .gitignore if a git repo is detected and the file isn't already ignored."""
    gitignore = Path(".gitignore")
    if not Path(".git").exists():
        return
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    if any(
        line.strip() in (".env", "*.env", ".env*")
        for line in existing.splitlines()
    ):
        return
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write("\n.env\n" if existing and not existing.endswith("\n") else ".env\n")
    console.print("[dim]Added .env to .gitignore[/dim]")


def _write_env(values: dict, path: Path) -> None:
    lines = [
        "# Generated by atlassian project init",
        f"ATLASSIAN_URL={values['atlassian_url']}",
        f"ATLASSIAN_EMAIL={values['atlassian_email']}",
        f"ATLASSIAN_API_TOKEN={values['atlassian_api_token']}",
        f"JIRA_PROJECT={values['jira_project']}",
        f"CONFLUENCE_SPACE={values['confluence_space']}",
        f"OLLAMA_HOST={values['ollama_host']}",
        f"OLLAMA_MODEL={values['ollama_model']}",
        f"OLLAMA_EMBED_MODEL={values['ollama_embed_model']}",
        "MEMORY_DB_PATH=~/.atlassian-cli/memory.db",
        "MEMORY_VECTOR_PATH=~/.atlassian-cli/vectors/",
        f"QA_BASE_URL={values.get('qa_base_url', '')}",
        f"MEMORY_BACKEND={values['memory_backend']}",
    ]
    if values.get("turso_url"):
        lines.append(f"TURSO_URL={values['turso_url']}")
    if values.get("turso_auth_token"):
        lines.append(f"TURSO_AUTH_TOKEN={values['turso_auth_token']}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


@app.command("init")
def init() -> None:
    """Interactive wizard to configure a new atlassian-cli project."""
    console.print(Panel(
        "Welcome to [bold]atlassian-cli[/bold] project setup.\n"
        "This wizard creates a [bold].env[/bold] file in the current directory.",
        title="[cyan]atlassian project init[/cyan]",
    ))

    # ── Resume check ─────────────────────────────────────────────────────
    collected: dict = {}
    resume_from = 0

    progress = _load_progress()
    if progress:
        completed = progress.get("completed_step", 0)
        next_step = completed + 1
        next_name = _STEP_NAMES.get(next_step)
        if next_name and typer.confirm(
            f"\nPrevious setup stopped before [bold]{next_name}[/bold]. Continue from there?",
            default=True,
        ):
            resume_from = next_step
            collected.update(progress.get("data", {}))
            console.print("  [dim]API token must be re-entered for security.[/dim]")
        else:
            _clear_progress()

    env_path = Path(".env")
    if not resume_from and env_path.exists():
        if not typer.confirm("\n.env already exists. Overwrite?", default=False):
            console.print("[dim]Cancelled.[/dim]")
            raise typer.Exit(0)

    # ── Step 1: Credentials (always re-entered) ──────────────────────────
    if resume_from > 0:
        console.print(f"\n[bold]Resuming from Step {resume_from}/5 — {_STEP_NAMES[resume_from]}[/bold]")
        console.print("[dim]Re-entering credentials is required for security.[/dim]")
    else:
        console.print("\n[bold]Step 1/5[/bold] — Atlassian Credentials")
    _url_default = collected.get("atlassian_url", "https://yourorg.atlassian.net")
    collected["atlassian_url"] = typer.prompt(
        "  Atlassian URL", default=_url_default
    ).rstrip("/")
    _email_kw: dict = ({"default": collected["atlassian_email"]} if "atlassian_email" in collected else {})
    collected["atlassian_email"] = typer.prompt("  Email", **_email_kw).strip()
    while True:
        token = typer.prompt("  API Token", hide_input=True).strip()
        if not token:
            console.print("  [red]Token cannot be empty, try again.[/red]")
            continue
        token2 = typer.prompt("  Confirm API Token", hide_input=True).strip()
        if token == token2:
            collected["atlassian_api_token"] = token
            console.print(f"  [dim]Token accepted ({len(token)} chars)[/dim]")
            break
        console.print("  [red]Tokens don't match, try again.[/red]")

    _jira = _atlassian_session(
        _Jira, collected["atlassian_url"],
        collected["atlassian_email"], collected["atlassian_api_token"],
    )
    _conf = _atlassian_session(
        _Confluence, collected["atlassian_url"],
        collected["atlassian_email"], collected["atlassian_api_token"],
    )

    with console.status("[bold green]Verifying credentials…[/bold green]"):
        try:
            _me = _jira.myself()
            _account_id = _me.get("accountId") if isinstance(_me, dict) else None
            console.print("[green]✓[/green] Credentials verified")
        except Exception as exc:
            msg = str(exc).lower()
            if "401" in str(exc) or "not authenticated" in msg or "unauthorized" in msg:
                console.print("[red]✗ Authentication failed.[/red] Check your email and API token.")
                console.print(
                    "  Create a token at: "
                    "[link=https://id.atlassian.com/manage-profile/security/api-tokens]"
                    "https://id.atlassian.com/manage-profile/security/api-tokens[/link]"
                )
            else:
                console.print(f"[red]✗[/red] Could not connect to Jira: {exc}")
            raise typer.Exit(1)

    # Preserve progress from previous steps already completed
    _save_progress(collected, max(1, resume_from - 1))

    # ── Step 2: Jira project ─────────────────────────────────────────────
    if resume_from > 2:
        console.print(f"\n[dim]Step 2/5 — Jira Project: {collected.get('jira_project')} ✓[/dim]")
    else:
        console.print("\n[bold]Step 2/5[/bold] — Jira Project")
        jira_choice = typer.prompt(
            "  (n) Create new project  (e) Use existing", default="e"
        ).strip().lower()

        if jira_choice == "n":
            proj_name = typer.prompt("  Project name")
            proj_key = typer.prompt("  Project key (e.g. MYAPP)").upper()
            with console.status("[bold green]Creating Jira project...[/bold green]"):
                try:
                    payload: dict = {
                        "key": proj_key,
                        "name": proj_name,
                        "projectTypeKey": "software",
                    }
                    if _account_id:
                        payload["leadAccountId"] = _account_id
                    _jira.create_project_from_raw_json(payload)
                    console.print(f"[green]✓[/green] Created Jira project: {proj_key}")
                except Exception as exc:
                    console.print(f"[red]✗[/red] Failed to create project: {exc}")
                    raise typer.Exit(1)
            collected["jira_project"] = proj_key
        else:
            proj_key = typer.prompt("  Project key", default="MYAPP").upper()
            try:
                _jira.project(proj_key)
                console.print(f"[green]✓[/green] Found Jira project: {proj_key}")
            except Exception:
                console.print(f"[yellow]⚠[/yellow]  Could not verify project {proj_key}.")
                if not typer.confirm("  Continue anyway (set manually in .env later)?", default=False):
                    raise typer.Exit(1)
            collected["jira_project"] = proj_key

        _save_progress(collected, 2)

    # ── Step 3: Confluence space ─────────────────────────────────────────
    if resume_from > 3:
        console.print(f"\n[dim]Step 3/5 — Confluence Space: {collected.get('confluence_space')} ✓[/dim]")
    else:
        console.print("\n[bold]Step 3/5[/bold] — Confluence Space")
        conf_choice = typer.prompt(
            "  (n) Create new space  (e) Use existing", default="e"
        ).strip().lower()

        if conf_choice == "n":
            space_name = typer.prompt("  Space name")
            space_key = typer.prompt("  Space key (e.g. DEV)").upper()
            with console.status("[bold green]Creating Confluence space...[/bold green]"):
                try:
                    _conf.create_space(space_key, space_name)
                    console.print(f"[green]✓[/green] Created Confluence space: {space_key}")
                except Exception as exc:
                    console.print(f"[red]✗[/red] Failed to create space: {exc}")
                    raise typer.Exit(1)
            collected["confluence_space"] = space_key
        else:
            space_key = typer.prompt("  Space key", default="DEV").upper()
            try:
                _conf.get_space(space_key)
                console.print(f"[green]✓[/green] Found Confluence space: {space_key}")
            except Exception:
                console.print(f"[yellow]⚠[/yellow]  Could not verify space {space_key}.")
                if not typer.confirm("  Continue anyway (set manually in .env later)?", default=False):
                    raise typer.Exit(1)
            collected["confluence_space"] = space_key

        _save_progress(collected, 3)

    # ── Step 4: Ollama ───────────────────────────────────────────────────
    if resume_from > 4:
        console.print(f"\n[dim]Step 4/5 — Ollama: {collected.get('ollama_model')} ✓[/dim]")
    else:
        console.print("\n[bold]Step 4/5[/bold] — Ollama Model")
        collected["ollama_host"] = typer.prompt(
            "  Ollama host", default=collected.get("ollama_host", "http://localhost:11434")
        )
        models = _ollama_list_models(collected["ollama_host"])

        if models:
            console.print("  Available models:")
            for i, m in enumerate(models, 1):
                console.print(f"    {i}. {m}")
            console.print("  Enter a number to select, or type a model name to download it.")
            raw = typer.prompt("  Model", default="1")
            if raw.isdigit() and 1 <= int(raw) <= len(models):
                collected["ollama_model"] = models[int(raw) - 1]
            else:
                collected["ollama_model"] = raw
                if raw not in models:
                    if typer.confirm(f"  Pull {raw}?", default=True):
                        with console.status(f"Pulling {raw}…"):
                            _ollama_pull(raw)
        else:
            console.print("  [dim](Ollama not reachable or no models installed)[/dim]")
            collected["ollama_model"] = typer.prompt(
                "  Model name", default=collected.get("ollama_model", "llama3.2")
            )

        embed_default = "nomic-embed-text"
        embed_hint = "[green]installed[/green]" if embed_default in models else "[yellow]not installed[/yellow]"
        collected["ollama_embed_model"] = typer.prompt(
            f"  Embed model  ({embed_hint})", default=embed_default
        )
        if collected["ollama_embed_model"] not in models:
            if typer.confirm(f"  Pull {collected['ollama_embed_model']}?", default=True):
                with console.status(f"Pulling {collected['ollama_embed_model']}…"):
                    _ollama_pull(collected["ollama_embed_model"])

        collected["qa_base_url"] = typer.prompt(
            "  QA base URL (optional, for test runner)", default=""
        )

        _save_progress(collected, 4)

    # ── Step 5: Memory backend ───────────────────────────────────────────
    console.print("\n[bold]Step 5/5[/bold] — Memory Backend")
    console.print("  (l) Local SQLite — works offline")
    console.print("  (t) Turso        — shared across machines")
    backend_choice = typer.prompt("  Backend", default="l").strip().lower()

    if backend_choice == "t":
        collected["memory_backend"] = "turso"
        if _turso_available():
            console.print("  [green]turso CLI detected[/green]")
            turso_action = typer.prompt(
                "  (n) Create new database  (e) Use existing", default="n"
            ).strip().lower()
            if turso_action == "n":
                db_name = typer.prompt("  Database name", default="atlassian-memory")
                with console.status("[bold green]Creating Turso database...[/bold green]"):
                    try:
                        url, tok = _turso_create_db(db_name)
                        collected["turso_url"] = url
                        collected["turso_auth_token"] = tok
                        console.print("[green]✓[/green] Turso database created")
                        console.print(f"  [dim]URL: {url}[/dim]")
                    except Exception as exc:
                        console.print(f"[yellow]⚠[/yellow] Turso creation failed: {exc}")
                        console.print("  [dim]Falling back to local SQLite — you can switch later.[/dim]")
                        collected["memory_backend"] = "local"
            else:
                collected["turso_url"] = typer.prompt("  TURSO_URL (libsql://...)")
                collected["turso_auth_token"] = typer.prompt(
                    "  TURSO_AUTH_TOKEN", hide_input=True
                )
        else:
            console.print(
                "  [yellow]turso CLI not found.[/yellow]  "
                "Install: [bold]npm install -g turso[/bold]"
            )
            collected["turso_url"] = typer.prompt("  TURSO_URL (libsql://...)")
            collected["turso_auth_token"] = typer.prompt(
                "  TURSO_AUTH_TOKEN", hide_input=True
            )
    else:
        collected["memory_backend"] = "local"

    # ── Write .env and clean up progress ─────────────────────────────────
    _write_env(collected, env_path)
    console.print(f"\n[green]✓[/green] Written: {env_path.resolve()}")
    _ensure_gitignored(env_path)
    _clear_progress()

    # ── Verify connections ───────────────────────────────────────────────
    console.print("\n[bold]Verifying connections…[/bold]")

    try:
        _jira.project(collected["jira_project"])
        console.print(f"[green]✓[/green] Jira ({collected['jira_project']})")
    except Exception:
        console.print(f"[red]✗[/red]  Jira ({collected['jira_project']})")

    try:
        _conf.get_space(collected["confluence_space"])
        console.print(f"[green]✓[/green] Confluence ({collected['confluence_space']})")
    except Exception:
        console.print(f"[red]✗[/red]  Confluence ({collected['confluence_space']})")

    _mock = types.SimpleNamespace(
        ollama_host=collected["ollama_host"],
        ollama_model=collected["ollama_model"],
        ollama_embed_model=collected["ollama_embed_model"],
    )
    if OllamaClient(_mock).ping():
        console.print(f"[green]✓[/green] Ollama ({collected['ollama_model']})")
    else:
        console.print(f"[red]✗[/red]  Ollama (not reachable at {collected['ollama_host']})")

    if collected.get("turso_url"):
        from atlassian_cli.integrations.turso import TursoHttpClient
        try:
            TursoHttpClient(
                collected["turso_url"], collected.get("turso_auth_token", "")
            ).execute("SELECT 1")
            console.print(f"[green]✓[/green] Turso ({collected['turso_url']})")
        except Exception:
            console.print("[red]✗[/red]  Turso (connection failed)")

    console.print(
        f"\n[green]Done![/green] Run [bold]atlassian feature create[/bold] to get started."
    )


# ── helpers for standardize ───────────────────────────────────────────────────

def _make_api_session(url: str, email: str, token: str) -> requests.Session:
    auth = base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")
    s = requests.Session()
    s.headers.update({"Authorization": f"Basic {auth}", "Accept": "application/json", "Content-Type": "application/json"})
    return s


def _api_get(session: requests.Session, base: str, path: str, params: dict | None = None) -> dict | list:
    r = session.get(f"{base}{path}", params=params)
    r.raise_for_status()
    return r.json()


def _api_post(session: requests.Session, base: str, path: str, data: dict) -> dict:
    r = session.post(f"{base}{path}", json=data)
    r.raise_for_status()
    return r.json()


def _api_put(session: requests.Session, base: str, path: str, data: dict) -> dict:
    r = session.put(f"{base}{path}", json=data)
    r.raise_for_status()
    return r.json() if r.text else {}


def _project_statuses(session: requests.Session, base: str, project_key: str) -> list[str]:
    """Return flat list of all status names for a project (across all issue types)."""
    try:
        data = _api_get(session, base, f"/rest/api/2/project/{project_key}/statuses")
        names: list[str] = []
        for itype in data:
            for s in itype.get("statuses", []):
                if s["name"] not in names:
                    names.append(s["name"])
        return names
    except Exception:
        return []


def _all_projects(session: requests.Session, base: str) -> list[dict]:
    """Paginate through all projects, requesting issue types in the expand."""
    projects: list[dict] = []
    start = 0
    while True:
        page = _api_get(session, base, "/rest/api/3/project/search", {
            "maxResults": 50, "startAt": start, "expand": "issueTypes",
        })
        projects.extend(page.get("values", []))
        if page.get("isLast", True):
            break
        start += len(page["values"])
    return projects


@app.command("standardize")
def standardize(
    reference: str = typer.Option("PYTHAGO", "--reference", "-r", help="Project key to copy workflow from"),
    dry_run: bool = typer.Option(False, "--dry-run", help="Preview changes without applying them"),
) -> None:
    """Apply Feature issue type (green) and reference-project workflow to every project missing them."""
    from atlassian_cli.config import get_settings
    settings = get_settings()

    base = settings.atlassian_url.rstrip("/")
    email = settings.atlassian_email
    token = settings.atlassian_api_token.get_secret_value()
    session = _make_api_session(base, email, token)

    # ── auth check ──────────────────────────────────────────────────────
    try:
        me = _api_get(session, base, "/rest/api/3/myself")
        console.print(f"[dim]Authenticated as {me['displayName']}[/dim]")
    except Exception as e:
        console.print(f"[red]✗[/red]  Auth failed — refresh your API token: {e}")
        raise typer.Exit(1)

    if dry_run:
        console.print("[yellow]DRY RUN — no changes will be made[/yellow]")

    # ── load all projects ────────────────────────────────────────────────
    with console.status("Loading projects…"):
        all_projects = _all_projects(session, base)

    console.print(f"[dim]{len(all_projects)} project(s) found[/dim]")

    # ── resolve reference project ────────────────────────────────────────
    ref = next((p for p in all_projects if p["key"] == reference), None)
    if not ref:
        console.print(f"[red]✗[/red]  Reference project '{reference}' not found.")
        raise typer.Exit(1)

    # ── reference workflow scheme ────────────────────────────────────────
    ref_wf_scheme_id: str | None = None
    try:
        wf_resp = _api_get(session, base, "/rest/api/3/workflowscheme/project", {"projectId": ref["id"]})
        entries = wf_resp.get("values", wf_resp) if isinstance(wf_resp, dict) else wf_resp
        if entries:
            entry = entries[0]
            ref_wf_scheme_id = str(
                entry.get("workflowScheme", entry).get("id", entry.get("id", ""))
            )
    except Exception as e:
        console.print(f"[yellow]⚠[/yellow]  Could not read {reference} workflow scheme: {e}")

    # ── check reference has IN QA ────────────────────────────────────────
    ref_statuses = _project_statuses(session, base, reference)
    in_qa_in_ref = any("IN QA" in s.upper() for s in ref_statuses)
    if not in_qa_in_ref:
        console.print(f"[yellow]⚠[/yellow]  '{reference}' has no 'IN QA' status — double-check the reference key.")

    # ── find or create Feature issue type (green = Story avatar) ────────
    all_types: list[dict] = _api_get(session, base, "/rest/api/3/issuetype")  # type: ignore[assignment]
    feature_type = next((t for t in all_types if t["name"].lower() == "feature"), None)

    if not feature_type:
        # Borrow the Story type's avatarId for a green icon; fall back to 10315
        story_type = next((t for t in all_types if t["name"].lower() == "story"), None)
        green_avatar = story_type.get("avatarId", 10315) if story_type else 10315
        if dry_run:
            console.print("[yellow]Would create:[/yellow] 'Feature' issue type (avatarId from Story)")
            feature_type = {"id": "__dry_run__", "name": "Feature"}
        else:
            try:
                feature_type = _api_post(session, base, "/rest/api/3/issuetype", {
                    "name": "Feature",
                    "description": "A new feature or product improvement",
                    "type": "standard",
                    "avatarId": green_avatar,
                })
                console.print(f"[green]✓[/green] Created 'Feature' issue type [id={feature_type['id']}]")
            except Exception as e:
                console.print(f"[red]✗[/red]  Could not create Feature issue type: {e}")
                raise typer.Exit(1)
    else:
        console.print(f"[dim]'Feature' issue type already exists (id={feature_type['id']})[/dim]")

    # ── process each project ─────────────────────────────────────────────
    changed = 0
    skipped = 0
    for project in all_projects:
        pkey = project["key"]
        if pkey == reference:
            continue

        pstyle = project.get("style", "classic")
        pname = project["name"]
        existing_type_names = {t["name"].lower() for t in project.get("issueTypes", [])}
        needs_feature = "feature" not in existing_type_names

        statuses = _project_statuses(session, base, pkey)
        needs_workflow = not any("IN QA" in s.upper() for s in statuses)

        if not needs_feature and not needs_workflow:
            console.print(f"[dim]{pkey:12} ✓  already standardized[/dim]")
            skipped += 1
            continue

        parts = []
        if needs_feature:
            parts.append("Feature type")
        if needs_workflow:
            parts.append("IN QA workflow")
        console.print(f"[yellow]{pkey:12}[/yellow]  needs: {', '.join(parts)}")

        if dry_run:
            continue

        # ─ add Feature issue type to this project's scheme
        if needs_feature:
            try:
                scheme_resp = _api_get(session, base, "/rest/api/3/issuetypescheme/project", {"projectId": project["id"]})
                scheme_entries = scheme_resp.get("values", [])
                if scheme_entries:
                    scheme_id = scheme_entries[0]["issueTypeScheme"]["id"]
                    _api_put(session, base, f"/rest/api/3/issuetypescheme/{scheme_id}/issuetype", {
                        "issueTypeIds": [feature_type["id"]],
                    })
                    console.print(f"  [green]✓[/green] Added Feature to {pkey}")
                    changed += 1
                else:
                    console.print(f"  [yellow]⚠[/yellow]  No issue type scheme found for {pkey}")
            except Exception as e:
                console.print(f"  [red]✗[/red]  Feature type: {e}")

        # ─ apply reference workflow scheme (classic projects only)
        if needs_workflow:
            if pstyle != "classic":
                console.print(f"  [dim]Workflow skipped — {pkey} is team-managed (next-gen); change workflow in the board settings[/dim]")
            elif not ref_wf_scheme_id:
                console.print(f"  [yellow]⚠[/yellow]  Workflow skipped — could not read {reference}'s scheme")
            else:
                try:
                    _api_put(session, base, f"/rest/api/3/workflowscheme/{ref_wf_scheme_id}/project", {
                        "projectId": project["id"],
                    })
                    console.print(f"  [green]✓[/green] Applied {reference} workflow to {pkey}")
                    changed += 1
                except Exception as e:
                    console.print(f"  [red]✗[/red]  Workflow: {e}")

    console.print(f"\n[bold]Done.[/bold] {changed} change(s) applied, {skipped} already compliant.")
