"""Headless project provisioning.

Everything the `atlassian project init` wizard does, minus the prompting and
the printing. `atlassian_cli.commands.project` is one front end over this;
supreme-leader's `init_project` MCP tool is the other. Functions here raise
typed errors instead of calling `typer.Exit`, so each front end decides how to
present a failure.
"""

from __future__ import annotations

import base64
import os
import subprocess
from pathlib import Path

import requests


class ProvisioningError(Exception):
    """Base class for every failure this module raises."""


class AuthError(ProvisioningError):
    """Atlassian credentials were rejected, or the instance is unreachable."""


class JiraError(ProvisioningError):
    """A Jira project could not be created or verified."""


class ConfluenceError(ProvisioningError):
    """A Confluence space could not be created or verified."""


# Patterns that already cover `.env`, so we do not append a duplicate line.
_ENV_EQUIVALENTS = {".env", "*.env", ".env*"}


def render_env(values: dict) -> str:
    """Return the text of a project `.env` file. Does not write anything."""
    lines = [
        "# Generated by atlassian project init",
        f"ATLASSIAN_URL={values['atlassian_url']}",
        f"ATLASSIAN_EMAIL={values['atlassian_email']}",
        f"ATLASSIAN_API_TOKEN={values['atlassian_api_token']}",
        f"JIRA_PROJECT={values['jira_project']}",
        f"CONFLUENCE_SPACE={values['confluence_space']}",
        "",
        "# --- AI (Ollama) ---",
        f"OLLAMA_HOST={values['ollama_host']}",
        f"OLLAMA_MODEL={values['ollama_model']}",
        f"OLLAMA_EMBED_MODEL={values['ollama_embed_model']}",
        "",
        "# --- Memory (per-project) ---",
        "MEMORY_DB_PATH=./memory/atlassian.db",
        "MEMORY_VECTOR_PATH=./memory/vectors/",
        f"QA_BASE_URL={values.get('qa_base_url', '')}",
        f"MEMORY_BACKEND={values['memory_backend']}",
    ]
    if values.get("turso_url") or values.get("turso_auth_token"):
        lines += ["", "# --- Turso (shared memory across machines) ---"]
    if values.get("turso_url"):
        lines.append(f"TURSO_URL={values['turso_url']}")
    if values.get("turso_auth_token"):
        lines.append(f"TURSO_AUTH_TOKEN={values['turso_auth_token']}")
    return "\n".join(lines) + "\n"


def ensure_gitignored(root: Path, entries: list[str]) -> list[str]:
    """Append each entry to `root/.gitignore` if absent. Returns what was added.

    A no-op outside a git repository — there is nothing to ignore yet.
    """
    root = Path(root)
    if not (root / ".git").exists():
        return []
    gitignore = root / ".gitignore"
    existing_text = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing = {line.strip() for line in existing_text.splitlines() if line.strip()}

    missing = []
    for entry in entries:
        covered = entry in existing or (
            entry == ".env" and existing & _ENV_EQUIVALENTS
        )
        if not covered:
            missing.append(entry)
    if not missing:
        return []

    prefix = "" if (not existing_text or existing_text.endswith("\n")) else "\n"
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write(prefix + "".join(f"{e}\n" for e in missing))
    return missing


def session(cls, url: str, email: str, token: str):
    """Instantiate an atlassian client with UTF-8 Basic auth.

    `requests._basic_auth_str` encodes credentials as latin-1, which raises
    UnicodeEncodeError for any non-latin-1 character. We bypass it by setting
    the Authorization header directly using UTF-8 (RFC 7617).
    """
    client = cls(url=url.rstrip("/"), cloud=True)
    auth = base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")
    client._session.headers["Authorization"] = f"Basic {auth}"
    client._session.auth = None  # stop residual session auth from interfering
    return client


def api_session(base: str, email: str, token: str) -> "requests.Session":
    """A plain requests session for the Jira REST endpoints the clients don't cover."""
    auth = base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")
    s = requests.Session()
    s.headers.update({
        "Authorization": f"Basic {auth}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    })
    return s


def verify_credentials(jira) -> str | None:
    """Return the caller's Atlassian accountId. Raises AuthError if rejected."""
    try:
        me = jira.myself()
    except Exception as exc:
        text = str(exc).lower()
        if "401" in str(exc) or "not authenticated" in text or "unauthorized" in text:
            raise AuthError(
                "Authentication failed — check the email and API token. Create one at "
                "https://id.atlassian.com/manage-profile/security/api-tokens"
            ) from exc
        raise AuthError(f"Could not connect to Jira: {exc}") from exc
    return me.get("accountId") if isinstance(me, dict) else None


def ollama_list_models(host: str) -> list[str]:
    """Model names installed on the Ollama host. Empty list if unreachable."""
    try:
        resp = requests.get(f"{host}/api/tags", timeout=5)
        resp.raise_for_status()
        return [m["name"] for m in resp.json().get("models", [])]
    except Exception:
        return []


def ollama_pull(model: str) -> bool:
    try:
        return subprocess.run(["ollama", "pull", model], timeout=300).returncode == 0
    except Exception:
        return False


def turso_available() -> bool:
    """True only if the turso CLI is actually runnable, not merely on disk.

    `shutil.which` finds .cmd wrappers on Windows that subprocess cannot run
    without shell=True, so we probe with a real invocation instead.
    """
    try:
        result = subprocess.run(
            ["turso", "--version"],
            capture_output=True, timeout=5, shell=(os.name == "nt"),
        )
        return result.returncode == 0
    except Exception:
        return False


def turso_create_db(db_name: str) -> tuple[str, str]:
    """Create a Turso database and return (url, auth_token)."""
    sh = os.name == "nt"  # .cmd wrappers on Windows require shell=True
    subprocess.run(["turso", "db", "create", db_name], check=True, shell=sh)
    url = subprocess.run(
        ["turso", "db", "show", db_name, "--url"],
        capture_output=True, text=True, check=True, shell=sh,
    ).stdout.strip()
    token = subprocess.run(
        ["turso", "db", "tokens", "create", db_name],
        capture_output=True, text=True, check=True, shell=sh,
    ).stdout.strip()
    return url, token
