"""Headless project provisioning.

Everything the `atlassian project init` wizard does, minus the prompting and
the printing. `atlassian_cli.commands.project` is one front end over this;
supreme-leader's `init_project` MCP tool is the other. Functions here raise
typed errors instead of calling `typer.Exit`, so each front end decides how to
present a failure.
"""

from __future__ import annotations

from pathlib import Path


class ProvisioningError(Exception):
    """Base class for every failure this module raises."""


class AuthError(ProvisioningError):
    """Atlassian credentials were rejected, or the instance is unreachable."""


class JiraError(ProvisioningError):
    """A Jira project could not be created or verified."""


class ConfluenceError(ProvisioningError):
    """A Confluence space could not be created or verified."""


# Patterns that already cover `.env`, so we do not append a duplicate line.
_ENV_EQUIVALENTS = {".env", "*.env", ".env*"}


def render_env(values: dict) -> str:
    """Return the text of a project `.env` file. Does not write anything."""
    lines = [
        "# Generated by atlassian project init",
        f"ATLASSIAN_URL={values['atlassian_url']}",
        f"ATLASSIAN_EMAIL={values['atlassian_email']}",
        f"ATLASSIAN_API_TOKEN={values['atlassian_api_token']}",
        f"JIRA_PROJECT={values['jira_project']}",
        f"CONFLUENCE_SPACE={values['confluence_space']}",
        "",
        "# --- AI (Ollama) ---",
        f"OLLAMA_HOST={values['ollama_host']}",
        f"OLLAMA_MODEL={values['ollama_model']}",
        f"OLLAMA_EMBED_MODEL={values['ollama_embed_model']}",
        "",
        "# --- Memory (per-project) ---",
        "MEMORY_DB_PATH=./memory/atlassian.db",
        "MEMORY_VECTOR_PATH=./memory/vectors/",
        f"QA_BASE_URL={values.get('qa_base_url', '')}",
        f"MEMORY_BACKEND={values['memory_backend']}",
    ]
    if values.get("turso_url") or values.get("turso_auth_token"):
        lines += ["", "# --- Turso (shared memory across machines) ---"]
    if values.get("turso_url"):
        lines.append(f"TURSO_URL={values['turso_url']}")
    if values.get("turso_auth_token"):
        lines.append(f"TURSO_AUTH_TOKEN={values['turso_auth_token']}")
    return "\n".join(lines) + "\n"


def ensure_gitignored(root: Path, entries: list[str]) -> list[str]:
    """Append each entry to `root/.gitignore` if absent. Returns what was added.

    A no-op outside a git repository — there is nothing to ignore yet.
    """
    root = Path(root)
    if not (root / ".git").exists():
        return []
    gitignore = root / ".gitignore"
    existing_text = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing = {line.strip() for line in existing_text.splitlines() if line.strip()}

    missing = []
    for entry in entries:
        covered = entry in existing or (
            entry == ".env" and existing & _ENV_EQUIVALENTS
        )
        if not covered:
            missing.append(entry)
    if not missing:
        return []

    prefix = "" if (not existing_text or existing_text.endswith("\n")) else "\n"
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write(prefix + "".join(f"{e}\n" for e in missing))
    return missing
