"""Headless project provisioning.

Everything the `atlassian project init` wizard does, minus the prompting and
the printing. `atlassian_cli.commands.project` is one front end over this;
supreme-leader's `init_project` MCP tool is the other. Functions here raise
typed errors instead of calling `typer.Exit`, so each front end decides how to
present a failure.
"""

from __future__ import annotations

import base64
import os
import subprocess
from pathlib import Path

import requests


class ProvisioningError(Exception):
    """Base class for every failure this module raises."""


class AuthError(ProvisioningError):
    """Atlassian credentials were rejected, or the instance is unreachable."""


class JiraError(ProvisioningError):
    """A Jira project could not be created or verified."""


class ConfluenceError(ProvisioningError):
    """A Confluence space could not be created or verified."""


# Patterns that already cover `.env`, so we do not append a duplicate line.
_ENV_EQUIVALENTS = {".env", "*.env", ".env*"}


def render_env(values: dict) -> str:
    """Return the text of a project `.env` file. Does not write anything."""
    lines = [
        "# Generated by atlassian project init",
        f"ATLASSIAN_URL={values['atlassian_url']}",
        f"ATLASSIAN_EMAIL={values['atlassian_email']}",
        f"ATLASSIAN_API_TOKEN={values['atlassian_api_token']}",
        f"JIRA_PROJECT={values['jira_project']}",
        f"CONFLUENCE_SPACE={values['confluence_space']}",
        "",
        "# --- AI (Ollama) ---",
        f"OLLAMA_HOST={values['ollama_host']}",
        f"OLLAMA_MODEL={values['ollama_model']}",
        f"OLLAMA_EMBED_MODEL={values['ollama_embed_model']}",
        "",
        "# --- Memory (per-project) ---",
        "MEMORY_DB_PATH=./memory/atlassian.db",
        "MEMORY_VECTOR_PATH=./memory/vectors/",
        f"QA_BASE_URL={values.get('qa_base_url', '')}",
        f"MEMORY_BACKEND={values['memory_backend']}",
    ]
    if values.get("turso_url") or values.get("turso_auth_token"):
        lines += ["", "# --- Turso (shared memory across machines) ---"]
    if values.get("turso_url"):
        lines.append(f"TURSO_URL={values['turso_url']}")
    if values.get("turso_auth_token"):
        lines.append(f"TURSO_AUTH_TOKEN={values['turso_auth_token']}")
    return "\n".join(lines) + "\n"


def ensure_gitignored(root: Path, entries: list[str], *,
                      force: bool = False) -> list[str]:
    """Append each entry to `root/.gitignore` if absent. Returns what was added.

    A no-op outside a git repository — there is nothing to ignore yet. The
    `.git` probe only recognises a repository *toplevel*, so a caller that
    already knows the directory is tracked (a path nested inside a larger repo,
    where `git rev-parse` says yes but there is no `.git` here) must pass
    `force=True`. A `.gitignore` in a subdirectory applies to that subtree, so
    writing one there is correct and sufficient.
    """
    root = Path(root)
    if not force and not (root / ".git").exists():
        return []
    gitignore = root / ".gitignore"
    existing_text = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing = {line.strip() for line in existing_text.splitlines() if line.strip()}

    missing = []
    for entry in entries:
        covered = entry in existing or (
            entry == ".env" and existing & _ENV_EQUIVALENTS
        )
        if not covered:
            missing.append(entry)
    if not missing:
        return []

    prefix = "" if (not existing_text or existing_text.endswith("\n")) else "\n"
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write(prefix + "".join(f"{e}\n" for e in missing))
    return missing


def basic_auth_value(email: str, token: str) -> str:
    """The base64 half of an HTTP Basic `Authorization` header, UTF-8 encoded.

    The single definition of how the credential is put on the wire. Callers that
    have to recognise it again — a token scrubber, for one — encode it the same
    way by calling this.
    """
    return base64.b64encode(f"{email}:{token}".encode("utf-8")).decode("ascii")


def basic_auth_header(email: str, token: str) -> str:
    """The full `Authorization` header value: `Basic <base64(email:token)>`."""
    return f"Basic {basic_auth_value(email, token)}"


def session(cls, url: str, email: str, token: str):
    """Instantiate an atlassian client with UTF-8 Basic auth.

    `requests._basic_auth_str` encodes credentials as latin-1, which raises
    UnicodeEncodeError for any non-latin-1 character. We bypass it by setting
    the Authorization header directly using UTF-8 (RFC 7617).
    """
    client = cls(url=url.rstrip("/"), cloud=True)
    client._session.headers["Authorization"] = basic_auth_header(email, token)
    client._session.auth = None  # stop residual session auth from interfering
    return client


def api_session(base: str, email: str, token: str) -> "requests.Session":
    """A plain requests session for the Jira REST endpoints the clients don't cover."""
    s = requests.Session()
    s.headers.update({
        "Authorization": basic_auth_header(email, token),
        "Accept": "application/json",
        "Content-Type": "application/json",
    })
    return s


def verify_credentials(jira) -> str | None:
    """Return the caller's Atlassian accountId. Raises AuthError if rejected."""
    try:
        me = jira.myself()
    except Exception as exc:
        text = str(exc).lower()
        if "401" in str(exc) or "not authenticated" in text or "unauthorized" in text:
            raise AuthError(
                "Authentication failed — check the email and API token. Create one at "
                "https://id.atlassian.com/manage-profile/security/api-tokens"
            ) from exc
        raise AuthError(f"Could not connect to Jira: {exc}") from exc
    return me.get("accountId") if isinstance(me, dict) else None


def ollama_list_models(host: str) -> list[str]:
    """Model names installed on the Ollama host. Empty list if unreachable."""
    try:
        resp = requests.get(f"{host}/api/tags", timeout=5)
        resp.raise_for_status()
        return [m["name"] for m in resp.json().get("models", [])]
    except Exception:
        return []


def ollama_pull(model: str) -> bool:
    try:
        return subprocess.run(["ollama", "pull", model], timeout=300).returncode == 0
    except Exception:
        return False


def turso_available() -> bool:
    """True only if the turso CLI is actually runnable, not merely on disk.

    `shutil.which` finds .cmd wrappers on Windows that subprocess cannot run
    without shell=True, so we probe with a real invocation instead.
    """
    try:
        result = subprocess.run(
            ["turso", "--version"],
            capture_output=True, timeout=5, shell=(os.name == "nt"),
        )
        return result.returncode == 0
    except Exception:
        return False


def turso_create_db(db_name: str) -> tuple[str, str]:
    """Create a Turso database and return (url, auth_token)."""
    sh = os.name == "nt"  # .cmd wrappers on Windows require shell=True
    subprocess.run(["turso", "db", "create", db_name], check=True, shell=sh)
    url = subprocess.run(
        ["turso", "db", "show", db_name, "--url"],
        capture_output=True, text=True, check=True, shell=sh,
    ).stdout.strip()
    token = subprocess.run(
        ["turso", "db", "tokens", "create", db_name],
        capture_output=True, text=True, check=True, shell=sh,
    ).stdout.strip()
    return url, token


# Full hierarchy: Epic → Feature → Story → Task/Sub-task → Bug.
# (name, description, avatarId, type)
ISSUE_TYPES: list[tuple[str, str, int, str]] = [
    ("Epic",     "A large body of work that can be broken down", 10307, "standard"),
    ("Feature",  "A new feature or product improvement",          10322, "standard"),
    ("Story",    "A user story",                                  10315, "standard"),
    ("Task",     "A small, concrete unit of work",                10318, "standard"),
    ("Sub-task", "A subtask within a task or story",              10316, "subtask"),
    ("Bug",      "A defect or unexpected behaviour",              10303, "standard"),
]


def _get(api, base: str, path: str, params: dict | None = None):
    resp = api.get(f"{base}{path}", params=params)
    resp.raise_for_status()
    return resp.json()


def _post(api, base: str, path: str, data: dict) -> dict:
    resp = api.post(f"{base}{path}", json=data)
    resp.raise_for_status()
    return resp.json()


def _put(api, base: str, path: str, data: dict) -> dict:
    resp = api.put(f"{base}{path}", json=data)
    resp.raise_for_status()
    return resp.json() if resp.text else {}


def ensure_jira_project(
    jira, api, base: str, key: str, *,
    name: str | None = None, create: bool = False, account_id: str | None = None,
) -> dict:
    """Verify a Jira project exists, creating it when `create` is set.

    Returns {"key", "created", "id"}. Raises JiraError if it is missing and
    `create` is False, or if creation fails.
    """
    key = (key or "").upper()
    if not key:
        raise JiraError("a Jira project key is required")

    try:
        data = jira.project(key)
        return {"key": key, "created": False, "id": str(data.get("id", ""))}
    except JiraError:
        raise
    except Exception as exc:
        if not create:
            raise JiraError(f"Jira project {key} not found: {exc}") from exc

    payload: dict = {"key": key, "name": name or key, "projectTypeKey": "software"}
    if account_id:
        payload["leadAccountId"] = account_id
    try:
        jira.create_project_from_raw_json(payload)
    except Exception as exc:
        raise JiraError(f"Failed to create Jira project {key}: {exc}") from exc

    try:
        data = jira.project(key)
        project_id = str(data.get("id", ""))
    except Exception:
        project_id = ""
    return {"key": key, "created": True, "id": project_id}


def ensure_issue_types(api, base: str, project_key: str) -> list[str]:
    """Add every missing type in ISSUE_TYPES to the project's scheme.

    Returns the names that were added. Raises JiraError if the project has no
    issue type scheme to modify.
    """
    base = base.rstrip("/")
    all_types: list[dict] = _get(api, base, "/rest/api/3/issuetype")
    project = _get(api, base, f"/rest/api/3/project/{project_key}")
    project_id = str(project.get("id", ""))
    existing_names = {t["name"].lower() for t in project.get("issueTypes", [])}
    existing_ids = {t["id"] for t in project.get("issueTypes", [])}

    to_add: list[str] = []
    added_names: list[str] = []
    for type_name, description, avatar, itype in ISSUE_TYPES:
        if type_name.lower() in existing_names:
            continue
        # A project-scoped type belongs to some other project — unusable here.
        global_type = next(
            (t for t in all_types
             if t["name"].lower() == type_name.lower() and not t.get("scope")),
            None,
        )
        if not global_type:
            global_type = _post(api, base, "/rest/api/3/issuetype", {
                "name": type_name, "description": description,
                "type": itype, "avatarId": avatar,
            })
        type_id = global_type.get("id")
        if type_id and type_id not in existing_ids:
            to_add.append(type_id)
            added_names.append(type_name)

    if not to_add:
        return []

    scheme = _get(api, base, "/rest/api/3/issuetypescheme/project",
                  {"projectId": project_id})
    entries = scheme.get("values", [])
    if not entries:
        raise JiraError(f"no issue type scheme found for project {project_key}")
    scheme_id = entries[0]["issueTypeScheme"]["id"]
    _put(api, base, f"/rest/api/3/issuetypescheme/{scheme_id}/issuetype",
         {"issueTypeIds": to_add})
    return added_names


def ensure_confluence_space(
    conf, key: str, *, name: str | None = None, create: bool = False,
) -> dict:
    """Verify a Confluence space exists, creating it when `create` is set."""
    key = (key or "").upper()
    if not key:
        raise ConfluenceError("a Confluence space key is required")
    try:
        conf.get_space(key)
        return {"key": key, "created": False}
    except Exception as exc:
        if not create:
            raise ConfluenceError(f"Confluence space {key} not found: {exc}") from exc
    try:
        conf.create_space(key, name or key)
    except Exception as exc:
        raise ConfluenceError(f"Failed to create Confluence space {key}: {exc}") from exc
    return {"key": key, "created": True}
